package dev.n0png.fieldops.core.map

/** GENERATED by scripts/build_us_state_geometry_pack.py. */
object Census2025UsState20mPackMetadata {
    const val UPSTREAM_FILENAME = "cb_2025_us_state_20m.zip"
    const val UPSTREAM_URL = "https://www2.census.gov/geo/tiger/GENZ2025/kml/cb_2025_us_state_20m.zip"
    const val UPSTREAM_SHA256 = "efddd884f1442ef233b1ba9c12dddbd66b6fdf94da6a373e1556aefe3dbc5751"
    const val UPSTREAM_SIZE_BYTES = 158017L
    const val PACK_ID = "us-census-cartographic-states"
    const val PACK_VERSION = "2025-20m-kml-v1"
    const val PACK_SHA256 = "5feb8c18688936a526523cb536766130be06b14ebfa918b3d99e39bfbcb0a130"
    const val SOURCE_VINTAGE = "2025"
    const val SOURCE_SCALE = "1:20,000,000"
    const val RETRIEVED_ON = "2026-10-06"
    const val BUILD_VERSION = "fieldops-cp0007c"
    const val RIGHTS = "U.S. Government work; U.S. copyright unavailable under 17 U.S.C. §105; Census Bureau source attribution requested"
    const val STATISTICAL_BOUNDARY_DISCLAIMER = "Census cartographic boundaries are intended for statistical mapping and are not legal land descriptions."
    const val UPSTREAM_PLACEMARK_COUNT = 52
    const val IGNORED_NON_WAS_PLACEMARK_COUNT = 2
    const val FEATURE_COUNT = 50
    const val ALASKA_POLYGON_COUNT = 47
    const val ALASKA_HAS_POSITIVE_LONGITUDES = true
    const val ALASKA_HAS_NEGATIVE_LONGITUDES = true
    const val ALASKA_MAX_LONGITUDE_JUMP = 0.980542000000014

    val featureSha256: Map<String, String> = linkedMapOf(
        "AK" to "83e5625eefcf7f3c17e81d0aca6fb46a87bcb02925b3e8d34d1d2f4855df69b1",
        "AL" to "459b972c1fc97f22e8ff74d0244d5e2e0b6fe3bc1ff2241146a4a4e81c2a3f25",
        "AR" to "1aefd832def651128c5bd9285be9d9597f18bb77ddf451b6ba501075b3a1f085",
        "AZ" to "f1aeed81302df20e4bcc40138eee6d60d7a6b92460099b4bb82f39c5c9fd3a2e",
        "CA" to "2df7ffa877deaf3426c58ba38406fad343ebdbf3eb07c2f9a082708fa28b188c",
        "CO" to "6df7715eedd4139eea85f365a3513dbf02758580210f743da3d0e57ef6b3d4cb",
        "CT" to "2c05ef410e83ca600fd50161cc1970878098a181b4e020d6a4a4d1a3be5cf31e",
        "DE" to "e29c01a9d61dd3f8978000e0e1f5a65e0fc755f60055456db5fc8f07d0cf6ce8",
        "FL" to "4f55c3156837808141fa9699425b7411b8454bca30ffae47f8b133cf27aff440",
        "GA" to "d07bf9ca74efcfd8d947836789e31aba7167be168ff67d75ae2cca6b8c9ea4a9",
        "HI" to "7c14d96c5f9bdb32c50d66285914b92a3ce17eb6655033c5e42e15b042eed7ca",
        "IA" to "300724201276067714647ba9a12b7cd3b142d4e88b6c0c0385208b4e642e0c09",
        "ID" to "ceed3fec83d411238b681343079415fd4d2be64ff7a6f2b0093908c436c0288a",
        "IL" to "9ba5df3a30535fc4acc74cb5abacb39dc0ea3e4d2cc6141deb83876bea95c530",
        "IN" to "efb1d8ebc2acc25593d297083cbcbd9a19c14ab3d525025878460c7c93900a08",
        "KS" to "7b7f31b8e43dbc9efe8fb35cb08380a893c0446a6bf24dd7479cd5f98af990fb",
        "KY" to "d2dfe4270263b6dc9d8c0e2ddfd0c33ecd4eb1a81f05fff1862ad387305c330d",
        "LA" to "028da7667b2f20ca7d040af90e2b825c21045c00d92af7aefc428155164ea436",
        "MA" to "45e361bf163073d480d109a21744defcaff95fb9c7586f3c33d270128d3394f1",
        "MD" to "a450c22de922d408a715de1b4b6d7f0ac77bfd3368ca9caceb6a062bd2b2bcb9",
        "ME" to "390dcabccb20cfaf00362f6409dd1ea861e39ae75f0c3451d24dda06ee590e8a",
        "MI" to "0e295e7147d909db8b7a39556bdd9fc067504d4c8dc2ca0dce1b4f593fbb80e1",
        "MN" to "95fef85472466a7f7f4d6f5bed6e412a7668545cf335614d155007d0b9a45e1d",
        "MO" to "87092d6a8f91450be6c9c5abd8338ade4b18be7a2ae255cdb435d152f1eb9e1b",
        "MS" to "c06e57d89a7147d8ee950d78ed15f3bf2af071c56a872fbea6d35e3ce2e4cb38",
        "MT" to "a88791122ac5d80a915022526970e6073a0ae3c9aa8b3e40dfb3ec2c62349974",
        "NC" to "a6ce4de44ae5846cdaa3768384df4a3c2c61e070f79afcc288ffc5575d9b6f1e",
        "ND" to "1a66a88e755d981a4401abaec1a9574111ea69d2600ed90783e2557677cf4a26",
        "NE" to "257380d1a695b464eb12ed9d5919f9b0c4656c88b2538a9db2ae0d7d5e95e90c",
        "NH" to "76774989355fe84076670b7f79721034cceb3b4aeddac91c0e0c02093d3114c0",
        "NJ" to "5172f70f61c9414d4268e385d6772645eff48b0e1e55d6b406b7fa5ffb83dbcb",
        "NM" to "37c7796eacca2b992796cae149f370326cf71216d4bd77ae5b23b1a582b1c6a8",
        "NV" to "2f4a708768bba02ff8e22bbccb230fdef098ba41c2ff99038d068879f5076532",
        "NY" to "53da693df263d1d40cd94bf177c678f87e9b9556504b24f67335ca9d35d45457",
        "OH" to "ac07b37572706d47b05dd931b39647e1fd757caf221491e0200c962010ab848c",
        "OK" to "dea1656dd553e76359fe468b2f906a8929116d0f407c2e13ca199524a6d82765",
        "OR" to "6109826c89aa23f8170013af46ded87572b7b7e87d6a708ce683b3e7cbe30343",
        "PA" to "d0d645e682dd8c3edadd1822e245319155a0b605fee22fa63e2fb72c36de9a97",
        "RI" to "efbf396d3be6924bb43c5cba4f08958b664922a510f6fde077fb2ef6c52e4d71",
        "SC" to "eefe9be4253735b2f62d9de18873260be9a35c10df64211bdb26b7eb260e3830",
        "SD" to "07e228072c22312662323adbb01e30202ff2879b279579edcb1411ba24a7dbcb",
        "TN" to "301fed761798c6a9173c4b2b422744c7aac612ede32a02a8de60d995011492ed",
        "TX" to "0fcd432531793e138dd065cdc1f48cac4d3286d984e9b5a2b0883a8328f5ad35",
        "UT" to "24ee4d2a031577cd08bf909b52a5648d8a4bba0e9c17d39d93b0957d6d64912a",
        "VA" to "fa82d2da825d57caac23bb322a7bea51a72fc475e4def6e54bc9584f8124df34",
        "VT" to "86eac2eba7241ea3a064a05a2a51603f614ebf5096b1a4531cdaf37caf7e8fee",
        "WA" to "75db0b60599fb94ec6fd45ef418f172ec81fe85e2ec36ce5100cfd7a9399a5b6",
        "WI" to "435989a6ee47caab1e26a09f0b65d47684af9505ef270be858c54068d1b63911",
        "WV" to "d2f209996bc5c682b66a22076acfd92d0a1ddfd36ce31f039f7c9f27706c2fc3",
        "WY" to "10ee6660008760766ed05097aebceed8886d862c9dc2e1060f822a6535e03798",
    )

    val polygonCounts: Map<String, Int> = linkedMapOf(
        "AK" to 47,
        "AL" to 1,
        "AR" to 1,
        "AZ" to 1,
        "CA" to 6,
        "CO" to 1,
        "CT" to 1,
        "DE" to 1,
        "FL" to 4,
        "GA" to 1,
        "HI" to 8,
        "IA" to 1,
        "ID" to 1,
        "IL" to 1,
        "IN" to 1,
        "KS" to 1,
        "KY" to 1,
        "LA" to 1,
        "MA" to 3,
        "MD" to 1,
        "ME" to 2,
        "MI" to 6,
        "MN" to 1,
        "MO" to 1,
        "MS" to 1,
        "MT" to 1,
        "NC" to 1,
        "ND" to 1,
        "NE" to 1,
        "NH" to 1,
        "NJ" to 1,
        "NM" to 1,
        "NV" to 1,
        "NY" to 2,
        "OH" to 2,
        "OK" to 1,
        "OR" to 1,
        "PA" to 1,
        "RI" to 2,
        "SC" to 1,
        "SD" to 1,
        "TN" to 1,
        "TX" to 1,
        "UT" to 1,
        "VA" to 2,
        "VT" to 1,
        "WA" to 2,
        "WI" to 3,
        "WV" to 1,
        "WY" to 1,
    )
}
