#!/usr/bin/env python3
import os
import pathlib
import re


def replace_one(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.S)
    if count != 1:
        raise SystemExit(f"Expected exactly one {label} section, found {count}")
    return updated


root = pathlib.Path(".")
run_id = os.environ["FINALIZE_RUN_ID"]
(root / "VERSION").write_text("v9-wspr-native-rx\n")

readme_path = root / "README.md"
readme = readme_path.read_text()

baseline = f"""## Verified durable baseline

**Latest verified checkpoint:** `CP-0002C-WSPR_NATIVE_RX`

Parent: `CP-0002B-JS8_NATIVE_TX`.

CP-0002C is a **GREEN host/CI receive-integration checkpoint with YELLOW Android/device status**. It replaces the saved WSPR receive stub with the exact pinned decoder path without claiming S23 Ultra / FTX-1 hardware proof or WSPR transmit support.

CP-0002C adds and proves:

- Decoder source is vendored from `Guenael/rtlsdr-wsprd@1ca9b83dd2562ce9ef2453aacdd5bc3aab982c7d`.
- CI verifies every vendored upstream file against its exact pinned Git blob ID; the upstream files remain unedited under `native/wspr/upstream/`.
- FieldOps converts one exact 120-second / 1,440,000-sample 12 kHz real PCM window to exactly 45,000 complex I/Q samples at 375 sps.
- The WSPR front end uses a 1500 Hz complex mixer and explicit FIR decimation stages of /4, /4 and /2.
- The pinned native `wspr_decode()` is reached through a FieldOps JNI boundary.
- Because the upstream decoder places large working buffers on the C stack, FieldOps invokes it on a dedicated native worker with an explicit 8 MiB stack instead of assuming a JVM/Android caller-thread stack size.
- A deterministic fixture generated by the pinned native `get_wspr_channel_symbols()` path is synthesized at 12 kHz, passed through the FieldOps receive front end, and correctly decoded as `K1JT FN20 20`.
- WSPR receive assertions pass **22/22**.
- Inherited JS8 receive/transmit regression remains green: **19 RX assertions and 39 TX assertions**.
- Inherited core regression remains green: **42,062 core assertions, 56 pipeline assertions and 19 LoTW assertions**.
- WSPR transmit remains deliberately unavailable from the production WSPR adapter until CP-0002D.

Pinned upstream WSPR source:

`Guenael/rtlsdr-wsprd@1ca9b83dd2562ce9ef2453aacdd5bc3aab982c7d`

Exact checked source/blob and integration evidence is recorded in `research/wspr/CP-0002C_WSPR_RX_INTEGRATION.md`.

- CP-0002C finalization workflow run: `{run_id}`

### Inherited verified ancestry

`CP-0002B-JS8_NATIVE_TX` remains the verified JS8 RX/TX parent checkpoint. `CP-0002A-JS8_NATIVE_RX` and `CP-0001-GITHUB_SURVEY` remain its verified ancestry.

### Android/device boundary

The pinned WSPR decoder uses the FFTW3 single-precision C API. CP-0002C validates that decoder on Linux/CI with `libfftw3f`; Android arm64-v8a packaging of WSPR + FFTW3 is **not** proven yet.

Actual Galaxy S23 Ultra execution, FTX-1 USB receive routing/levels, and off-air WSPR reception are also **not** device-tested. WSPR RF transmit is intentionally outside this checkpoint.

"""

readme = replace_one(
    readme,
    r"## Verified durable baseline\n.*?\n## Engineering rules",
    baseline + "## Engineering rules",
    "verified durable baseline",
)

readme = readme.replace(
    "- Current Git source baseline: `CP-0002B-JS8_NATIVE_TX`",
    "- Current Git source baseline: `CP-0002C-WSPR_NATIVE_RX`",
    1,
)

wspr_path = """For WSPR RX, the 12 kHz branch continues through:

`12 kHz real -> 1500 Hz complex mixer -> FIR /4 -> FIR /4 -> FIR /2 -> 375 sps complex I/Q -> pinned wspr_decode()`

The resulting WSPR decoder window is exactly 45,000 complex samples over 120 seconds.

"""
anchor = "FT8/FT4/FT2 and WSPR use time-window logic appropriate to each protocol.\n\n"
if wspr_path not in readme:
    if anchor not in readme:
        raise SystemExit("Expected shared-RX WSPR anchor was not found")
    readme = readme.replace(anchor, anchor + wspr_path, 1)

next_section = """## Current exact next action

**CP-0002D — WSPR native TX only.**

1. Use the pinned upstream WSPR channel-symbol encoder; do not invent a separate message codec.
2. Synthesize the 162-symbol 4-FSK waveform in the FieldOps 12 kHz TX domain.
3. Preserve the protocol invariants: 8192 samples/symbol at 12 kHz, 1.46484375 Hz tone spacing, 1,327,104 total samples and 110.592 seconds of encoded waveform.
4. Route the complete WSPR waveform only through the existing FieldOps radio arbiter/PTT/audio owner.
5. Prove WSPR cannot compete with another TX owner and every failure/cancel path returns to RX-safe state with `TX0`, audio stopped and ownership released.
6. Do not start CP-0002E native-mode regression until the focused CP-0002D transmit gate is green.
7. Keep RF level, ALC, spectrum and actual S23 Ultra + FTX-1 transmission status YELLOW/RED until hardware testing.

"""

readme = replace_one(
    readme,
    r"## Current exact next action\n.*?\n## README maintenance contract",
    next_section + "## README maintenance contract",
    "current exact next action",
)
readme_path.write_text(readme)

(root / "NEXT_ACTION.md").write_text(
    """# NEXT ACTION — FTX-1 FieldOps

**CP-0002D — WSPR native TX only**

Use the pinned WSPR channel-symbol encoder and synthesize the complete 12 kHz 4-FSK waveform: 162 symbols, 8192 samples per symbol, 1.46484375 Hz tone spacing, 1,327,104 samples total, 110.592 seconds. Route that waveform only through the common FieldOps TX arbiter/PTT/audio path and prove no competing owner can transmit and all error/cancel paths collapse to RX with `TX0`, audio stopped and ownership released.

Do **not** start the broader CP-0002E native-mode regression until CP-0002D is green. Actual RF output/ALC/spectrum remains hardware-gated.
"""
)

history_path = root / "checkpoints" / "CHECKPOINT_HISTORY.md"
history = history_path.read_text()
if "## CP-0002C — WSPR native RX" not in history:
    history = history.rstrip() + "\n\n" + f"""## CP-0002C — WSPR native RX

Parent: `CP-0002B-JS8_NATIVE_TX`

FieldOps now receives WSPR through the exact pinned rtlsdr-wsprd decoder. The 12 kHz real receive window is mixed and FIR-decimated to the decoder's 375 sps complex-I/Q domain, and a pinned native encoder fixture is recovered end-to-end as `K1JT FN20 20`. Exact vendored upstream Git blobs are verified in CI. WSPR transmit remains unavailable until CP-0002D.

Host/CI gate: core 42,062; pipeline 56; LoTW 19; WSPR RX 22; JS8 RX 19; JS8 TX 39 assertions, all PASS.

Finalization workflow run: `{run_id}`.

Evidence: `research/wspr/CP-0002C_WSPR_RX_INTEGRATION.md`.
"""
    history_path.write_text(history)
